services:
  crytractor.api:
    image: crytractor.api
    container_name: crytractor.api
    build:
      context: .
      dockerfile: src/CryTraCtor.API/Dockerfile
    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: ${DATABASE_URL}
      FILE_STORAGE_DIRECTORY: ${FILE_STORAGE_DIRECTORY}
    depends_on:
        - postgres

  postgres:
    image: postgres:17.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
