services:
  crytractor.api:
    image: crytractor.api
    build:
      context: ./src/CryTraCtor.API
      dockerfile: src/CryTraCtor.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - postgres
  
  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - "5432:5432"