services:
  crytractor.postgres:
    image: postgres:17.3
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
