// <auto-generated />
using System;
using CryTraCtor.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryTraCtor.Database.Migrations
{
    [DbContext(typeof(CryTraCtorDbContext))]
    partial class CryTraCtorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryTraCtor.Database.Entities.CryptoProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CryptoProduct");
                });

            modelBuilder.Entity("CryTraCtor.Database.Entities.KnownDomainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CryptoProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CryptoProductId");

                    b.ToTable("KnownDomain");
                });

            modelBuilder.Entity("CryTraCtor.Database.Entities.StoredFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("InternalFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicFileName")
                        .IsUnique();

                    b.ToTable("StoredFile");
                });

            modelBuilder.Entity("CryTraCtor.Database.Entities.KnownDomainEntity", b =>
                {
                    b.HasOne("CryTraCtor.Database.Entities.CryptoProductEntity", "CryptoProduct")
                        .WithMany("KnownDomains")
                        .HasForeignKey("CryptoProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoProduct");
                });

            modelBuilder.Entity("CryTraCtor.Database.Entities.CryptoProductEntity", b =>
                {
                    b.Navigation("KnownDomains");
                });
#pragma warning restore 612, 618
        }
    }
}
